version: '3.5'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/PostgreSQL:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - pm-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "roqls23@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Fl@m3ng0"
    ports:
      - "6543:80"
    depends_on:
      - postgresql
    networks:
      - pm-network


networks:
  pm-network:
    driver: bridge